import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import DashboardProvier from "./dashboard/DashboardProvier"
import GlobalProvier from "./GlobalProvier"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvier>{children}</GlobalProvier>
      </body>
    </html>
  )
}
